<?php
$_CFG_MAIL_FROM            = 'myJAM <myjam@example.com>';
$_CFG_MAIL_REPLY_TO        = 'myjam@example.com';
$_CFG_MAIL_ENVELOPE_SENDER = 'myjam@example.com';
$_CFG_MAIL_SIGNATURE       = "\n---------------------------------------------------------------------------------------------------------\n"
                            ."This mail was automatically generated by <myJAM/> - The Sophisticated Job Accounting and Monitoring Tool\n\n"
                            ."If you think, you have received this email by mistake, pleases contact webmaster@example.com\n";
